version: '3'
services:
  db:
    image: mysql:5.7
    ports:
     - 3306:3306
    volumes:
     - ./DB/mysql:/var/lib/mysql
     - ./DB/init:/docker-entrypoint-initdb.d
     - ./DB/config:/etc/mysql/mysql.conf.d
    environment:
     -  MYSQL_ROOT_PASSWORD=hogehoge

  python:
    image: python:3.7
    tty: true

  nginx:
    image: nginx:latest
    ports:
     - 80:80
    volumes:
     - ./nginx:/etc/nginx/conf.d
    depends_on:
      - python
      - db
    tty: true