version: '3'
services:
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
     - "3306:3306"
    expose:
      - "3306"
    volumes:
     - ./DB/mysql:/var/lib/mysql
     - ./DB/init:/docker-entrypoint-initdb.d
     - ./DB/config:/etc/mysql/mysql.conf.d
    environment:
     -  MYSQL_ROOT_PASSWORD=hogehoge
    tty: true

  python:
    image: python:3.7
    container_name: apiServer
    ports:
      - "8000:80"
    expose: 
      - "80"
    volumes:
      - ./python/src:/usr/src
    command: /bin/sh -c "pip install -r /usr/src/requirements.txt && python /usr/src/main.py"
    environment: 
      - WEB_API_PORT=80
    tty: true

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
     - 80:80
    volumes:
     - ./nginx:/etc/nginx/conf.d
    tty: true