@startuml
title マッチングの仕組み
participant ClientA
participant APIServer
participant RoomServer
database Redis
database MySQL
ClientA -> APIServer : オンライン対戦開始ボタンを押す
APIServer -> Redis : 対戦待機のキューに積む
APIServer -> ClientA : 認証情報付与(キューの一意値)
RoomServer -> Redis : キュー情報取得
alt Redisに二人以上の情報が存在するか
    RoomServer -> MySQL : ルーム作成
    RoomServer -> Redis : ユーザー情報削除
end
loop 部屋が存在するか
    alt ClientA が一定時間リクエストがない場合
        RoomServer -> Redis : キュー情報削除
    end

    ClientA -> APIServer: 部屋があるか確認  (ロングポーリング)
    APIServer -> MySQL : ルーム情報取得
    APIServer -> ClientA : 部屋が存在しているか情報を返す & 部屋が存在するなら先手か後手か情報を渡す

end
@enduml