@startuml
Presenter o-- Board
Board *-- Piece
iView <.. Presenter
iView <|.. view
BoardStateListener <|.. Presenter
BoardStateListener <-- Board
iPresenter <|.. Presenter
iPresenter <.. view

class Board {
    - pieces: List<Piece>
    - turn: Int
    + initBoard()
    + getTurn(): Int
    + putPiece(x, y)
    + checkPuttablePosition(x, y): Boolean
    + checkPuttablePosition(): List<Piece>
    + countBlackPiece(): Int
    + countWhitePiece(): Int
    - setTurn(Int)
}

interface BoardStateListener {
    + puttedPiece(piece: Piece)
    + reversedPiece(piece: Piece)
    + nextTurn(turn: Int)
    + pass()
    + finishGame()
}

class Piece {
    - int status
    - int x
    - int y
    + reversePiece()
}

interface iView {
    + onStart()
    + onClickPauseButton()
    + onClickBoardPosition(x: Int, y: Int)
}

class view {}

interface iPresenter {
    showPutPiece(x: Int, y: Int, color: Int)
    showReversePiece(x: Int, y: Int, color: Int)
    showWhiteCount(n: Int)
    showBlackCount(n: Int)
    showPause()
    showPass()
    showTurn(color: Int)
    showResult(winnerColor: Int)
    throwErrorText(text: String)
}
class Presenter {

}
@enduml
