@startuml
IBoardController <-- Board
IBoardState <-- Board
IBoardController <|.. BoardController
BoardState *-- Piece
BoardState *-- Turn
BoardStateListener <|.. Presenter
Board <-- Presenter
iPresenter <|.. Presenter
iView <-- Presenter
iView <|.. view
iPresenter <-- view
BoardStateListener <-- BoardController
IBoardState <|.. BoardState

class Board {}

class BoardController {}

interface IBoardController {
    + initBoard()
    + getTurn(): Turn
    + putPiece(x, y)
    + checkPuttablePosition(x, y): Boolean
    + checkPuttablePosition(): List<Piece>
    + countBlackPiece(): Int
    + countWhitePiece(): Int
    - setTurn(Turn)
}

class BoardState {
    - pieces: List<Piece>
    - turn: Turn
}

interface IBoardState {
    + getPieces(): List<Piece>
    + getTurn(): Turn
}

enum Turn {
    + BLACK
    + WHITE
}

interface BoardStateListener {
    + puttedPiece(piece: Piece)
    + reversedPiece(piece: Piece)
    + nextTurn(turn: Turn)
    + pass()
    + finishGame()
}

class Piece {
    - Turn status
    - int x
    - int y
    + reversePiece()
}

interface iPresenter {
    + onStart()
    + onClickPauseButton()
    + onClickBoardPosition(x: Int, y: Int)
}

class view {}

interface iView {
    showPutPiece(x: Int, y: Int, color: Turn)
    showReversePiece(x: Int, y: Int, color: Turn)
    showWhiteCount(n: Int)
    showBlackCount(n: Int)
    showPause()
    showPass()
    showTurn(color: Turn)
    showResult(winner: Turn)
    throwErrorText(text: String)
}
class Presenter {

}
@enduml
