name: CI

on:
  push:
    branches: 
      - develop
        
jobs:
  build-and-push:
    runs-on: ubuntu-18.04
    timeout-minutes: 300

    steps:
    - uses: actions/checkout@v1
  
 #ここからはフロントのテスト
  
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
  #デバッグ用ビルド
    - name: Build of Debug
      run: gradle assembleDebug
        
  #テストコードを回す
    - name: Build of test
      run: gradle test
       
       

