name: CI

on:
  push:
    branches: 
      - develop
  pull_request:
    branches: 
      - develop
        
jobs:
  my-job:
    name: Job
    runs-on: ubuntu-latest
    steps:
      - name: Running APIServer
        run: |
          ls && \
          ls ./..
